### ISSUE TITLE
New Release

### ISSUE THREAD

**Issue by jimmynotjim** [yeoman/generator-webapp#267]
The latest release is from Nov 26th but the readme includes instructions for libsass, which wasn't merged until Dec 24th. The readme should probably be downgraded to show the instructions for the 0.2.0 release or a new release should be created and published to NPM.

**Comment by tonilaukka** [comment]
I was just wondering the same. I read the instructions and it looked exactly what I needed, but soon discovered that npm has an older version. Is there a way to use the latest version?

**Comment by silvenon** [comment]
Yes, and I recommend it until we speed up our release cycles.

```sh
$ git clone https://github.com/yeoman/generator-gulp-webapp
$ cd generator-gulp-webapp
$ npm link
```

Now `yo gulp-webapp` will use that repo. To update, simply navigate to `generator-gulp-webapp` and do `git pull`.

The reason why we're not releasing yet is that we're waiting for libsass to solve their blocker issues, like support for nested `@media` queries.

P.S. If you want to view the readme of a specific version, simply select that tag on GitHub.

**Comment by jimmynotjim** [comment]
Any reason why the `master` branch isn't the latest stable release? A lot of new people might not know they need to go digging to find the correct readme or files and it'd solve a lot of confusion I've seen. I only became aware of the ruby/libsass difference because a friend was stuck trying to figure out why his gulpfile didn't match the one in `master`. Creating an unstable pre-release or development branch for new work would easily solve that.

**Comment by sindresorhus** [comment]
This is how most projects do git.

**Comment by silvenon** [comment]
If we were to create a `dev` branch, we would have to make it the default, so people don't submit PRs to `master`. If `dev` is the default branch, people viewing the repo will again see the "wrong" readme.

**Comment by jimmynotjim** [comment]
@silvenon thanks for the explanation. I knew most OSS projects organize this way but never understood why, especially when nearly every document on Git says `master` should be stable and deployable. It's certainly a hurdle for newer developers to get over and I was just trying to think of a way to make it easier.

**Comment by kevva** [comment]
I wouldn't say that `master` should be considered stable or release ready. Look at the tags instead.

**Comment by sindresorhus** [comment]
> It's certainly a hurdle for newer developers to get over and I was just trying to think of a way to make it easier.

Are you sure it's not just you. This is the first time I've ever got a complaint about this.

**Comment by jimmynotjim** [comment]
It wasn't even me, and yes, this did happen to a friend. He found the repo, saw what he liked, NPM installed and ended up wasting a bunch of time trying to figure out why his installed files didn't match master. The bottom line is we take things like this for granted because we're used to it. What we don't realize is there's a lot of little "you have to have experienced it before" situations that make entering the development world harder than it needs to be.

I never really thought much about it before now because like you said, it's how most projects do it and I've been involved with OSS for a few years. Now that I'm seeing it through his eyes, I'm questioning why.  I only opened this issue because he had already given up and moved on to another project. I figured it was worth mentioning in hopes of preventing the same situation in the future. 

As far as never having complaints, did you stop to think your reaction is why? I know a lot of developers that don't open issues or contribute to OSS projects for this exact reason. We're all adults, no one wants to be treated like a student being chided by their teacher. I know you are responsible for a really large number of libraries and get more issues than most of us, but have a little patience with people and when someone asks "why", have the empathy to answer honestly.

**Comment by silvenon** [comment]
I agree that sometimes a gap can happen, as master is the bleeding edge and some drastic changes can happen that aren't yet released. Some projects **do** have a `dev` and a `master` branch, but I think that workflow is much more useful in larger projects. As I explained, having a `dev` branch will not solve this problem, because it would still be the first thing that the user sees.

Concerning complaints and reactions, anyone who got their hands dirty in OSS should find it natural that `master` is the bleeding-edge and that you're usually going to see it if you go to a library's source code. I think this is how most people do it and rethinking it seems like too much work (e.g. you would need to change how GitHub does it) because of one wrong gut feeling. Some things are non-intuitive and mistakes of the designer, but sometimes users make mistakes too.

Nobody was rude to you, we're putting effort into explaining this to you.

**Comment by jimmynotjim** [comment]
I appreciate you taking the time to explain it. Now when people ask I have something to tell them besides ¯\_(ツ)_/¯. Also, my comment was in direct reply to "Are you sure it's not just you." Sorry if you though it was toward you, your replies were all helpful.

**Comment by eddiemonge** [comment]
Did you read the actual readme for that release? https://www.npmjs.com/package/generator-gulp-webapp shows the readme relevant for that release. The readme on github shows the relevant one for that version (unreleased but still install by `npm i -g yeoman/generator-gulp-webapp`. If you look at a readme for some other version then it is very understandable that it might not be relevant. Thats why you should always look at the one for the version of the thing you are using.

**Comment by sindresorhus** [comment]
> As far as never having complaints, did you stop to think your reaction is why?

Yes, that's why I was asking if you're sure it's not just you. If this is a common problem I'm amazed now is the first time I'm hearing about it.

> I know a lot of developers that don't open issues or contribute to OSS projects for this exact reason. We're all adults, no one wants to be treated like a student being chided by their teacher. I know you are responsible for a really large number of libraries and get more issues than most of us, but have a little patience with people and when someone asks "why", have the empathy to answer honestly.

I think you're reading too much into my comment. I'm only curious about why, definitely not trying belittle anyone. Sorry for my brevity, I was on my phone. But you got your answer, so hope that's ok.

-

If this is such a common misconception someone should really write a blog post on how it works. Hint hint ;)
