### ISSUE TITLE
please implement gulp serve:dist

### ISSUE THREAD

**Issue by aguegu** [yeoman/generator-webapp#287]
grunt version got that ...

**Comment by Mystist** [comment]
:+1:

**Comment by silvenon** [comment]
Now Gulp version does too!

**Comment by arthurvr** [comment]
Yay! Thanks @silvenon!

**Comment by fernoftheandes** [comment]
I just ran `yo gulp-webapp` on an empty directory using the latest release, 0.3.0, after I added the `serve:dist` task that I copied from commit a74a08f. I built it using `gulp build` and then ran `gulp serve:dist`. What opened in the browser was a directory listing of the `dist` dir. 

Do I need to do something else besides copying the `serve:dist` task into my `gulpfile.js` from release 0.3.0?

Thanks!

**Comment by silvenon** [comment]
Hey. I removed the directory listing feature in c1104ecdb049e7011b73703a2d2d5799f49ad331 because I don't know whether it's possible to do it well in our circumstances. But that is only problematic in `gulp serve`, `gulp serve:dist` should work fine even with the directory listing. I tried it now myself.

**Comment by silvenon** [comment]
Yep, removing `directory: true` will fix it. Obviously it doesn't work the way we thought it did.

**Comment by fernoftheandes** [comment]
Thanks @silvenon, and it's very helpful to have the console logs tell whether the files are being served from `app` or `dist`.

**Comment by silvenon** [comment]
Yeah, BrowserSync is really awesome.
