### ISSUE TITLE
Sass is not recompiled on change.

### ISSUE THREAD

**Issue by fseminario** [yeoman/generator-webapp#296]
I am making changes to the scss files in /bower_components/bootstrap-sass-official/assets/stylesheets/bootstrap/, but there is no Autoreload or any compiling occurring. I spent some time tweaking the gulpfile.js but had no success. Anything I am supposed to do to get this to work?

**Comment by silvenon** [comment]
You should not change anything in the `bower_components` directory, because:

* other people won't get your changes, because it's excluded from version control
* once you update your package, your changes will be overridden

Packages should never be modified directly. You can override variables by placing them in `main.css` before `@import`ing Bootstrap.

Let me know if you need further explanation :smiley:

**Comment by fseminario** [comment]
Thank you explaining this and both points make sense. It took me a bit of time to figure out to put the variables BEFORE the @import. I am up and running once again. Cheers!

**Comment by silvenon** [comment]
:+1:
