### ISSUE TITLE
Adding REST API Support to gulp task in webapp

### ISSUE THREAD

**Issue by charumaheshwari** [yeoman/generator-webapp#378]
Adding REST API Support to gulp task in webapp

I am setting a new web project, using yeoman generator: https://github.com/yeoman/generator-gulp-webapp, I also have a set of REST APIs in a small app.js express server.

At the moment, the default gulp serve task from that generator simply serves static contents.

I'd like to add REST API support to the webapp, such that when serve task is active, I can open an URL, let's say http://localhost:9000/about and my REST API renders about.html in browser.

app.get('/about', function(req, res) {
    res.render('about.html');
});

Note: I want the task to run in all three modes : development, dist and test.

**Comment by silvenon** [comment]
Hey :smiley: This generator **is** intended for static content and single-page apps. Users might have very different stacks so we don't want to assume anything because no stack is the best. I.e. the best stack for you is the one you feel most comfortable in.

You could try if a [different generator](http://yeoman.io/generators/) suits you better. E.g. search for "express".
