### ISSUE TITLE
Why the external css not added to index.html?

### ISSUE THREAD

**Issue by zhouhao27** [yeoman/generator-webapp#401]
I run the following command:

> bower install ihover --save

But the css of ihover is not added to my index.html. Is there a way to add external css when I run bower install? Thanks.

**Comment by alferov** [comment]
CSS isn't added to your index.html because ihover has [invalid bower.json](https://github.com/gudh/ihover/blob/gh-pages/bower.json). `generator-gulp-webapp` uses `wiredep` to wire installed dependencies with the source code.
According `wiredep` docs:

>**What can go wrong?**
 - A Bower package may not properly list its dependencies in its bower.json file.
 - A Bower package may not specify a main property in its bower.json file.

If you take a look at [ihover bower.json](https://github.com/gudh/ihover/blob/gh-pages/bower.json) you will notice that depended assets (like styles and scripts) are not specified in `main` property (there is no `main` property at all).
Example of correct [twitter bootstrap bower.json](https://github.com/twbs/bootstrap/blob/master/bower.json).

Conclusion: It's not a `generator-gulp-webapp` issue.

**Comment by silvenon** [comment]
Thanks @alferov :+1: 

Also, make sure that `gulp serve` is running while you install dependencies (with correct `bower.json`s :sweat_smile:). Read [this](https://github.com/yeoman/generator-gulp-webapp/tree/master/docs#bower) for more info.
