### ISSUE TITLE
sass not working 

### ISSUE THREAD

**Issue by mortennh** [yeoman/generator-webapp#494]
i'm importing sass-files in my main.scss but it seems that gulp serve is ignoring any changes in these files - only on the initial startup.

here's how my main.scss looks like:

```
$icon-font-path: '../fonts/';

// bower:scss
@import 'bower_components/bootstrap-sass/assets/stylesheets/_bootstrap.scss';
// endbower

@import '_fonts', '_variables', '_start-article-grid'; 
```

I did not change the gulpfile. Do i have to add something specific to get the webapp working with sass?

any help would be great! thanks

**Comment by silvenon** [comment]
It should work out of the box. Are you running v2.0.0? Do you have JavaScript enabled?

**Comment by abondarenko** [comment]
The same issue.
Bower injects the wrong path. Should be 
@import "../../bower_components/bootstrap-sass/assets/stylesheets/_bootstrap.scss";

**Comment by silvenon** [comment]
It should work without `../../` because we're [modifying Sass load paths](https://github.com/yeoman/generator-webapp/blob/25b0f3560211207f3cf2c27bacae2d46ded28758/app/templates/gulpfile.js#L18) to include the project root directory. Are you getting an error? Does it happen with a fresh install or have you changed something?

**Comment by abondarenko** [comment]
Fresh install.
It seems there were no errors when I started, but Webstorm (IDE that I use) said there was an error with path.

**Comment by silvenon** [comment]
This is because of modified load paths. I guess this approach is problematic if you have any kind of path checking 😕 You could remove [this line](https://github.com/yeoman/generator-webapp/blob/25b0f3560211207f3cf2c27bacae2d46ded28758/app/templates/gulpfile.js#L181) from your gulpfile and run `gulp wiredep` again to fix all the paths within `bower:scss` comments.

**Comment by abondarenko** [comment]
Thanks.
