### ISSUE TITLE
generator-webapp UNMET PEER DEPENDENCY

### ISSUE THREAD

**Issue by sevenmaxis** [yeoman/generator-webapp#582]
```
megas@mbp ~$ npm install -g generator-webapp
Users/megas/.npm-packages/lib
├── generator-webapp@2.2.0
└── UNMET PEER DEPENDENCY yo@>=1.7.1

npm WARN generator-webapp@2.2.0 requires a peer of yo@>=1.7.1 but none was installed.
```

But yeoman version 1.8.5 is installed

OSX Sierra 10.12.1

**Comment by sindresorhus** [comment]
This is not the place to post about npm install. Use the official npm support channels for that.

**Comment by CyberPunkCodes** [comment]
The trick is to do:

`npm install -g yo generator-webapp`

Since they wouldn't help you, I will.

This SHOULD be documented HERE in your README for the install instructions. This is a common problem on OSX. You have to specify it at the same time, or it isn't smart enough to find it.

Newbies trying to install your "generator-webapp" on OSX will have a heck of a time installing it if they don't know this. Which is why YOU should document it!

**Comment by eddiemonge** [comment]
This is only a warning, not an error. And it is an npm bug.
