### ISSUE TITLE
Add support for gulp-modernizr

### ISSUE THREAD

**Issue by addyosmani** [yeoman/generator-webapp#6]
https://github.com/doctyper/gulp-modernizr

**Comment by ahmadalfy** [comment]
Modernizr is now 3.5 and gulp-modernizr is working. Can we add this?

**Comment by silvenon** [comment]
@ahmadalfy are you up for a PR? Otherwise I'll add this when I find time.

**Comment by ahmadalfy** [comment]
@silvenon sure, will do

**Comment by ahmadalfy** [comment]
@silvenon I am done with the integration https://github.com/ahmadalfy/generator-webapp/commit/497d043aa0c16c3e236fe13238ee24968ecd426d but there is a minor issue I am not sure how to tackle. Modernizr used to ship with a build with all the available tests. Since version 3 it require that you [build your own version](https://github.com/Modernizr/Modernizr/issues/1759) with your the tests you choose. gulp-modernizr will take care of that of course during the build but the problem now is during development. There is no file to develop against. There is currently 2 options I think:

1. Change this in the HTML code
```html
    <!-- build:js scripts/vendor/modernizr.js -->
    <script src="/bower_components/modernizr/modernizr.js"></script>
    <!-- endbuild -->
```
to be
```html
    <!-- build:js scripts/vendor/modernizr.js -->
    <!--<script src="/bower_components/modernizr/modernizr.js"></script>-->
    <!-- endbuild -->
```
to avoid the 404 during the development and add a notice that the user should navigate to `bower_components/modernizr` then run `npm install` then `grunt` to create the full version then uncomment that line.

2. Using npm scripts to add a postinstall hook to automatically create a Modernizr build.

What do you guys think?

**Comment by silvenon** [comment]
In [v4.0.0-0](https://github.com/yeoman/generator-webapp/releases/tag/v4.0.0-0) we're configuring Modernizr through a config file.
