### ISSUE TITLE
Yeoman + gulp + PHP 

### ISSUE THREAD

**Issue by Migacz85** [yeoman/generator-webapp#655]
Hi Guys!
Awesome work with this tool. For front end its a fantastic tool. But is a chance to connect this somehow to work with php and mysql ? I found some steps but for grunt. But i love GULP :) It would be sweet to have installer with possibility to add this functionality... (*dreaming).  But can somebody help me with proper configuration of these?

**Comment by silvenon** [comment]
Hey @Migacz85, I don't work with PHP and MySQL, so I may not be very useful. I know that wiredep supports PHP files, so you should be able to set up dependency injection. Minification is also probably a matter of replacing `.html` with `.php`, with the possible exception of HTML minification (although maybe that's supported as well).

Have you tried to do this? Where did you get stuck?

I'll close this because it's not an issue with the generator, but we can continue the discussion.

**Comment by Migacz85** [comment]
Hello @silvenon Thank You for response i didint now where exactly I can put my question wich is not a bug releated but more a configure related. Some directions ? I was trying few options, but each time i had a php  turn on other things wasnt working. I will keep in mind your tip and try this when i will come back from holiday.

**Comment by silvenon** [comment]
You can share your repo with your starter PHP and MySQL setup and I can help you that way.
