### ISSUE TITLE
New Update without Bower?

### ISSUE THREAD

**Issue by dertuerke** [yeoman/generator-webapp#700]
Hi,

Is a new update planned without Bower?

**Comment by neilhem** [comment]
Hi, we are going to release a release without Bower, but there are some blocking issues

**Comment by cesarferreira** [comment]
what's wrong with bower, not cool anymore? Moving to `npm` ?

**Comment by neilhem** [comment]
Bower authors announced deprecation of bower and as an alternative using npm/yarn.

**Comment by san983** [comment]
Hi @neilhem is there a thread for this? https://github.com/yeoman/generator-webapp/issues/700#issuecomment-347492542 

I'm willing to help, thanks!

**Comment by xied75** [comment]
Any updates? Is this still in plan?

**Comment by spetrey** [comment]
Is still in the pipeline? I'm assuming there are still some major blocking issues. How can we help?

**Comment by silvenon** [comment]
@smpetrey thanks for offering to help! A PR containing following changes would be immensely appreciated:

## Update all Yeoman dependencies

Those would probably these three:

  - `yeoman-generator`
  - `generator-mocha`
  - `generator-jasmine`

## Replace Bower and wiredep with npm

This means that from now on users will have to link dependencies manually from `node_modules` manually, instead of automatically from `bower_components`.

## Tests

Ensuring that every combination of options returns an expected new output would be great.

**Comment by UlisesGascon** [comment]
Hi @smpetrey & @silvenon! Can I help here?

**Comment by silvenon** [comment]
Sure @UlisesGascon! This didn't really take off, so if you'd like to take on this upgrade, I'd be more than happy!

**Comment by UlisesGascon** [comment]
@silvenon  Sure! I will start soon ;-)

**Comment by UlisesGascon** [comment]
@silvenon do you want to create a dedicated branch, like `legacy-bower`? I think that this change will be a major one xD

**Comment by silvenon** [comment]
I'm not sure. Bower is deprecated so I don't know if keeping a legacy branch is necessary. Are you asking because we might potentially backport some fixes to that branch?

**Comment by UlisesGascon** [comment]
Oh! Well... I saw [legacy-grunt](https://github.com/yeoman/generator-webapp/tree/legacy-grunt), but it is ok for me to keep the same branches as we have today ^^

**Comment by silvenon** [comment]
The difference is that Grunt isn't deprecated.

**Comment by UlisesGascon** [comment]
One more question... Bower will be replaced with NPM, that is an easy change.

About ` Wiredep`,  I was thinking about  [babelify](https://www.npmjs.com/package/babelify) and [browserify](http://browserify.org/), but I am not sure if we want to keep this behaviour/feature or not.

Maybe... you have a better proposal?

**Comment by silvenon** [comment]
For this upgrade let's have users include assets manually, then gulp-useref and other tools will do their thing. In the future I was thinking about adding webpack or maybe a simpler bundler if you have an idea. I've heard good things about Parcel, but I never used it myself.

**Comment by UlisesGascon** [comment]
Let me make this change now and then we will discuss about Parcel or Webpack. I was looking for an excuse to learn Parcel, to be honest :trollface:

**Comment by UlisesGascon** [comment]
I saw that bower is very integrated with the generator so I will split this task in few little issues in order to split the job and let others the opportunity to join, if you agree... ^^

### Main Topics (current step)
- [x] Remove Bower/Wiredep/etc...
    - [x] Migrate Bower dependencies to NPM (BS3, BS4)
    - [x] Rewrite `app/templates/index.html`, etc...
    - [x] Update gulp tasks (remove wiredep/bower related ones and add new ones of needed)
    - [x] Remove unnecessary files
- [ ] Remove Bower references from Documentation (`recipes`, `app/USAGE`,  `README.md`, etc...)
- [ ] Update Tests

Note: I am thinking to add a tasks in gulp to copy bootstrap `dist` files from `./node_modules/..` to `./app` and then `./dist`, so there won't be a reference to `node_modules` in the `index.html`

**Comment by silvenon** [comment]
Even though this is a big migration, I think it's best if it was a part of a single PR. Multiple people can collaborate on a single PR, though. 😄

The task list is really comprehensive and seems to include everything that's necessary for the migration 👍 About your last note, I think it's unnecessary to add a special task for Bootstrap because it is just one of the dependencies, users might add more, so they would need to reference `node_modules` in `index.html` in that case anyway. I think it would be an unnecessary amount of work, especially since we're planning a module bundler in the long run.

**Comment by UlisesGascon** [comment]
Awesome! Fully agree on that... We can keep the `node_modules` as expected, also I agree to keep all in one single PR ;-)

**Comment by 47ronin** [comment]
> This means that from now on users will have to link dependencies manually from `node_modules` manually, instead of automatically from `bower_components`

Was this meant to be an improvement in the scaffolding process? ☹️

**Comment by UlisesGascon** [comment]
@47ronin right now Bower is deprecated. But you can still use this version of the generator with `npm install -g generator-webapp@3.0.1`.

In the future we will improve this flow using Parcel or Webpack. btw... PRs are more than welcome ;-)

**Comment by ElenaMLopez** [comment]
Tx a lot for the work @UlisesGascon !!! 😻

**Comment by 47ronin** [comment]
Thanks, @UlisesGascon for the feedback. I am hopeful the process will be as simple and intuitive as it used to be with **Bower**. A lot of webdevs at my humble skill level flocked to this workflow because of Bower's simplicity and expressiveness.

For those who still want to use **Bower** temporarily with the **Boostrap 4** option of **generator-webapp**, you can use this `bower.json`:

```
{
  "name": "your-project-name",
  "private": true,
  "dependencies": {
    "bootstrap": "~4.2.1",
    "jquery": "^3.3.1"
  },
  "devDependencies": {
    "chai": "^4.2.0",
    "mocha": "^6.0.0-1"
  },
  "overrides": {
    "bootstrap": {
      "main": [
        "dist/css/bootstrap.css",
        "dist/js/bootstrap.js"
      ]
    }
  }
}

```
…Then run `bower install` to download and inject the proper dependencies. `gulp serve` to continue normal development.

**Comment by silvenon** [comment]
Removed Bower in [v4.0.0-0](https://github.com/yeoman/generator-webapp/releases/tag/v4.0.0-0)!
